// Code generated by github.com/wzbwzt/stringerMsg DO NOT EDIT

// Package example const code comment msg
package example

// noErrorMsg if code is not found, GetMsg will return this
const noErrorMsg = "unknown error"

// messages get msg from const comment
var messages = map[Code]string{

	ErrCodeHasNotExist: "has not exist",
	ErrParams:          "err params",
	ErrServer:          "Internal Server Error",
}

// String return string
func (code Code) String() string {
	return GetMsg(code)
}

// GetMsg get error msg
func GetMsg(code Code) string {
	var (
		msg string
		ok  bool
	)
	if msg, ok = messages[code]; !ok {
		msg = noErrorMsg
	}
	return msg
}
